### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by ntthanh** [r509/r509#120]
Hi Team,

I am from the world of the EJBCA and MSCA, and have some quick questions:
- Does R509 support HSM?
- Does R509 support Multiple CAs. In EJBCA, I can create multiple CAs. But in MSCA, you can create one CA for a Server. What's about R509?
- Does it have CRL management tool: Full CRL, delta CRL, etc
- Does it have a RA interface to manage certificate requests, certificates, CAs, certificate templates, end entities, etc
- Has it been ready for Clustering setup?
- Does it support Certificate Transparency, SCEP?
- For some type of certificates that requires custom OIDs, can this be configured in R509?

Thanks a lot in advance! Because I could find clear information and I am not ruby developer, so I have to ask you such the questions.
Best,
Thanh

**Comment by reaperhulk** [comment]
Hi @ntthanh,

r509 does support HSMs, but only in the context of OpenSSL ENGINEs. Familiarity with that system is generally required.

Yes, you can create multiple CAs.

CRL management is present -- full CRL only, no delta CRL.

A registration authority is not provided.

r509 is really a base upon which you build a CA. Doing high availability/clustering is left to the people building on it.

It does not support CT or SCEP at this time (CT because it was only a proposal when I originally wrote this).

Custom OIDs are technically possible but you have to reach into the dark heart of the system, so not really.

Hopefully that helps.

**Comment by ntthanh** [comment]
Thank you very much for your clarification. It helps.

have a nice day!
Thanh
