### ISSUE TITLE
Domain expired?

### ISSUE THREAD

**Issue by kyrias** [r509/r509#121]
It seems like the r509.org domain has expired, was this lapse intentional?

**Comment by reaperhulk** [comment]
Good question. I suppose the answer is yes since I did see it expiring and chose not to renew. It was my assumption (perhaps incorrect?) that no one really used r509.org to access the project. Given the limited level of activity on GitHub it's hard for me to tell how many users of r509 there are.

I would love to find additional maintainers to improve r509 and lead it forward since the majority of my time is actually spent in Python these days, but that's a topic for a separate issue!

**Comment by kyrias** [comment]
The website is useful for the docs, though that should be easy to move to GitHub Pages.  Anyway, I don't use it often anymore, but whenever I need to do some CA work it's what I reach for, since there's not really anything nicer!
